# Generated by Django 3.2.13 on 2022-06-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_id',
            new_name='client_uuid',
        ),
    ]
