# Generated by Django 3.2.13 on 2022-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_identifying_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
