# Generated by Django 3.2.13 on 2022-08-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaymentsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.CharField(max_length=300)),
                ('payment_dest', models.CharField(max_length=300)),
                ('internal_request_id', models.CharField(max_length=300)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('response_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('response_id', models.CharField(blank=True, max_length=300, null=True)),
                ('respone_status', models.CharField(blank=True, max_length=300, null=True)),
                ('result_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('result_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
