# Generated by Django 3.2.13 on 2022-06-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWalletDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('use_type_code', models.CharField(blank=True, max_length=300, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_description', models.CharField(blank=True, max_length=300, null=True)),
                ('client_uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('use_level', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
