# Generated by Django 3.2.13 on 2022-06-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientwalletdirectory',
            old_name='client_uuid',
            new_name='client_ref',
        ),
    ]
