# Generated by Django 3.2.13 on 2022-08-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_rename_client_uuid_clientwalletdirectory_client_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwalletdirectory',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
