# Generated by Django 3.2.13 on 2022-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_clientwalletdirectory_creation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwalletdirectory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
