# Generated by Django 3.2.13 on 2022-08-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0006_auto_20220830_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('internal_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=300, null=True)),
                ('trans_code', models.CharField(blank=True, max_length=300, null=True)),
                ('money_provider_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('initial_response_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('callback_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('callback_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsTransactionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet_ref', models.CharField(max_length=100)),
                ('initiate_payment', models.BooleanField(default=True)),
                ('payment_inintiated', models.BooleanField(default=False)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('payment_dest', models.CharField(max_length=300)),
                ('provider_transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.walletrecords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletPaymentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet_ref', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('provider_url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletPaymentsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_id', models.CharField(max_length=300)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('result_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('result_timestamp', models.DateTimeField(blank=True, null=True)),
                ('result_status', models.CharField(blank=True, max_length=300, null=True)),
                ('provider_transaction_code', models.CharField(blank=True, max_length=300, null=True)),
                ('transaction_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstransactionmonitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
