# Generated by Django 3.2.13 on 2022-09-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCollectionsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_id', models.CharField(max_length=300)),
                ('transaction_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstransactionmonitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
