# Generated by Django 3.2.13 on 2022-07-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_mobileloans_client_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproductcharges',
            name='charge_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
