# Generated by Django 3.2.13 on 2022-08-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20220813_1626'),
        ('lending', '0003_loanproductcharges_charge_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLoanActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('loan_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('action_code', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.CharField(blank=True, max_length=100, null=True)),
                ('action_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('loan_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('lower_limit', models.CharField(max_length=100)),
                ('upper_limit', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileLoanProductCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('loan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_code', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_frequency', models.CharField(max_length=100)),
                ('charge_moment', models.CharField(max_length=100)),
                ('charge_value_type', models.CharField(max_length=100)),
                ('charge_value', models.CharField(max_length=100)),
                ('charge_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.mobileloanproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='client',
        ),
        migrations.DeleteModel(
            name='LoanProductCharges',
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='disbursment_trans_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LoanProduct',
        ),
    ]
