# Generated by Django 3.2.13 on 2022-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_auto_20220813_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileloanproduct',
            name='lower_limit',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobileloanproductcharges',
            name='charge_destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobileloanproductcharges',
            name='charge_frequency',
            field=models.CharField(default='oneoff', max_length=100),
        ),
    ]
