# Generated by Django 3.2.13 on 2022-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_auto_20220817_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileloans',
            name='dsbsment_credit_part_tran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
