# Generated by Django 3.2.13 on 2022-08-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_mobileloans_dsbsment_credit_part_tran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileLoanActions',
        ),
    ]
