# Generated by Django 3.2.13 on 2022-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_delete_mobileloanactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileloanproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileloanproductcharges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
