# Generated by Django 3.2.13 on 2022-08-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20220830_0315'),
        ('clients', '0008_alter_branches_created_at'),
        ('lending', '0008_auto_20220824_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAmotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan_ref', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('amount_due', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAmotizationPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('loan_amotization_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.loanamotization')),
                ('wallet_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.walletrecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
