# Generated by Django 3.2.13 on 2022-09-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0007_cinregistry_created_at'),
        ('lending', '0009_loanamotization_loanamotizationpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileloans',
            old_name='dsbsment_credit_part_tran',
            new_name='disbursment_credit_part_tran',
        ),
        migrations.AddField(
            model_name='mobileloanproduct',
            name='interest_realization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobileloanproduct',
            name='loan_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobileloanproduct',
            name='penalty_grace_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileloanproduct',
            name='penalty_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='cin',
            field=models.ManyToManyField(blank=True, null=True, to='cin.CINRegistry'),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='penalty_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='penalty_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileloans',
            name='unrealized_interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mobileloanproduct',
            name='lower_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mobileloanproduct',
            name='upper_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mobileloans',
            name='amount_disbursed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mobileloans',
            name='applied_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
