# Generated by Django 3.2.13 on 2022-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_auto_20220905_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileLoans',
        ),
    ]
