# Generated by Django 3.2.13 on 2022-09-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0011_delete_mobileloans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileLoanProductCharges',
        ),
    ]
