# Generated by Django 3.2.13 on 2022-09-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0007_cinregistry_created_at'),
        ('clients', '0008_alter_branches_created_at'),
        ('lending', '0013_delete_mobileloanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProductCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan_code', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_code', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_frequency', models.CharField(default='oneoff', max_length=100)),
                ('charge_moment', models.CharField(max_length=100)),
                ('charge_value_type', models.CharField(max_length=100)),
                ('charge_value', models.CharField(max_length=100)),
                ('charge_destination', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan_code', models.CharField(max_length=100)),
                ('loan_type', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('lower_limit', models.FloatField(default=0.0)),
                ('upper_limit', models.FloatField(default=0.0)),
                ('interest_realization', models.CharField(blank=True, max_length=30, null=True)),
                ('loan_period', models.CharField(blank=True, max_length=30, null=True)),
                ('penalty_period', models.CharField(blank=True, max_length=20, null=True)),
                ('penalty_grace_period', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan_type_code', models.CharField(max_length=100)),
                ('loan_ref', models.CharField(max_length=100)),
                ('applied_amount', models.FloatField(default=0.0)),
                ('amount_disbursed', models.FloatField(default=0.0)),
                ('loan_status', models.CharField(max_length=100)),
                ('applied_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_applied', models.CharField(max_length=100)),
                ('date_disbursed', models.DateField(blank=True, null=True)),
                ('date_cleared', models.DateField(blank=True, null=True)),
                ('loan_wallet_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('disbursment_trans_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('disbursment_credit_part_tran', models.CharField(blank=True, max_length=100, null=True)),
                ('penalty_start', models.DateTimeField(blank=True, null=True)),
                ('penalty_end', models.DateTimeField(blank=True, null=True)),
                ('unrealized_interest', models.FloatField(default=0.0)),
                ('securities_value', models.FloatField(default=0.0)),
                ('securities_coverage', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.ManyToManyField(to='cin.CINRegistry')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
