# Generated by Django 3.2.13 on 2022-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0002_remove_cinregistry_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinregistry',
            name='client_ref',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
