# Generated by Django 3.2.13 on 2022-08-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0003_cinregistry_client_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinregistry',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
