# Generated by Django 3.2.13 on 2022-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0004_cinregistry_creation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinregistry',
            name='owner_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
