# Generated by Django 3.2.13 on 2022-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0006_remove_cinregistry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinregistry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
