# Generated by Django 3.2.13 on 2022-08-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cin', '0004_cinregistry_creation_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('debit_part_trans', models.IntegerField(blank=True, default=1, null=True)),
                ('credit_part_trans', models.IntegerField(blank=True, default=1, null=True)),
                ('initiated_by', models.CharField(blank=True, max_length=300, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=300, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_action', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_record_id', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('record_type', models.CharField(blank=True, max_length=300, null=True)),
                ('record_amount', models.FloatField(default=0.0)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('related_source', models.CharField(blank=True, max_length=500, null=True)),
                ('related_source_ref', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(max_length=300)),
                ('scheme_code', models.CharField(default='NM100', max_length=300)),
                ('wallet_type', models.CharField(max_length=300)),
                ('wallet_name', models.CharField(max_length=300)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=300)),
                ('cin', models.ManyToManyField(to='cin.CINRegistry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
