# Generated by Django 3.2.13 on 2022-06-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerWalletRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('record_type', models.CharField(blank=True, max_length=300, null=True)),
                ('record_amount', models.FloatField(default=0.0)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=300, null=True)),
                ('post_deposit_calls', models.BooleanField(default=False)),
                ('post_withdraw_calls', models.BooleanField(default=False)),
                ('cin', models.ManyToManyField(to='cin.CINRegistry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanWalletRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('record_type', models.CharField(blank=True, max_length=300, null=True)),
                ('record_amount', models.FloatField(default=0.0)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormalWalletRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('record_type', models.CharField(blank=True, max_length=300, null=True)),
                ('record_amount', models.FloatField(default=0.0)),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('debit_part_trans', models.IntegerField(blank=True, default=1, null=True)),
                ('credit_part_trans', models.IntegerField(blank=True, default=1, null=True)),
                ('initiated_by', models.CharField(blank=True, max_length=300, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=300, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_action', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_record_id', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoansDirectory',
            fields=[
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=300, null=True)),
                ('post_deposit_calls', models.BooleanField(default=False)),
                ('post_withdraw_calls', models.BooleanField(default=False)),
                ('loan_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='banking.loanwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=300, null=True)),
                ('post_deposit_calls', models.BooleanField(default=False)),
                ('post_withdraw_calls', models.BooleanField(default=False)),
                ('cin', models.ManyToManyField(to='cin.CINRegistry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('wallet_name', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField(default=0.0)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('allow_overdraw', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('scheme_code', models.CharField(blank=True, max_length=300, null=True)),
                ('post_deposit_calls', models.BooleanField(default=False)),
                ('post_withdraw_calls', models.BooleanField(default=False)),
                ('cin', models.ManyToManyField(to='cin.CINRegistry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
