# Generated by Django 3.2.13 on 2022-08-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsTransactionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(max_length=100)),
                ('initiate_payment', models.BooleanField(default=True)),
                ('payment_inintiated', models.BooleanField(default=False)),
                ('payment_status', models.CharField(max_length=100)),
                ('wallet_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.walletrecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
