# Generated by Django 3.2.13 on 2022-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerwallet',
            name='scheme_code',
            field=models.CharField(default='000', max_length=300),
        ),
        migrations.AlterField(
            model_name='ledgerwallet',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ledgerwallet',
            name='wallet_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ledgerwallet',
            name='wallet_ref',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loansdirectory',
            name='scheme_code',
            field=models.CharField(default='000', max_length=300),
        ),
        migrations.AlterField(
            model_name='loansdirectory',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loansdirectory',
            name='wallet_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loansdirectory',
            name='wallet_ref',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='scheme_code',
            field=models.CharField(default='000', max_length=300),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='wallet_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loanwallet',
            name='wallet_ref',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='normalwallet',
            name='scheme_code',
            field=models.CharField(default='000', max_length=300),
        ),
        migrations.AlterField(
            model_name='normalwallet',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='normalwallet',
            name='wallet_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='normalwallet',
            name='wallet_ref',
            field=models.CharField(max_length=300),
        ),
    ]
