# Generated by Django 3.2.13 on 2022-07-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0003_cinregistry_client_ref'),
        ('banking', '0002_auto_20220630_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerwallet',
            name='cin',
        ),
        migrations.AddField(
            model_name='ledgerwallet',
            name='cin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cin.cinregistry'),
        ),
    ]
