# Generated by Django 3.2.13 on 2022-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_paymentstransactionmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaymentsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('amount', models.CharField(max_length=300)),
                ('payment_dest', models.CharField(max_length=300)),
                ('internal_request_id', models.CharField(max_length=300)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('response_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('response_id', models.CharField(blank=True, max_length=300, null=True)),
                ('respone_status', models.CharField(blank=True, max_length=300, null=True)),
                ('result_payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('result_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletPaymentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('wallet_ref', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentstransactionmonitor',
            name='destination_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
