# Generated by Django 3.2.13 on 2022-08-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20220822_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsrecords',
            name='created_at',
        ),
    ]
