# Generated by Django 3.2.13 on 2022-07-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20220712_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerwalletrecords',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loanwalletrecords',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='normalwalletrecords',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
