# Generated by Django 3.2.13 on 2022-08-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20220824_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPaymentsRecords',
        ),
        migrations.RemoveField(
            model_name='paymentstransactionmonitor',
            name='wallet_record',
        ),
        migrations.DeleteModel(
            name='WalletPaymentsDetails',
        ),
        migrations.DeleteModel(
            name='PaymentsTransactionMonitor',
        ),
    ]
