# Generated by Django 3.2.13 on 2022-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20220830_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet_ref', models.CharField(max_length=300)),
                ('lien_amount', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=100)),
                ('done_by', models.CharField(blank=True, max_length=30, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
